export enum EActions {
  ShowCommands = "commands",
  Go = "go",
  Quit = "quit",
  StartFight = "fight",
  LookAt = "look at",
  TakeItem = "take",
  Attack = "attack",
  TalkTo = "talk to",
  ShowInventory = "inventory",
  BuyItem = "buy",
  ExamineItem = "examine",
  ConsumeItem = "consume",
  DropItem = "drop",
  NewGame = "new game",
  SaveGame = "save",
  CloseSequence = "close",
}